### ISSUE TITLE
Checklist for next release

### ISSUE THREAD

**Issue by felipenoris** [felipenoris/AWSFinance#11]
- [x] add Julia 0.5 installation
- [x] add IJulia kernel for Julia 0.5
- [x] fix python's distribution package installation
- [x] check if it´s possible to use a single LLVM installation
- [x] update Python version
- [x] use virtualenv so that jupyter´s kernel and packages use Python 2.7.12
